### ISSUE TITLE
Update ukbnmr to work with the UKB RAP

### ISSUE THREAD

**Issue by sritchie73** [sritchie73/ukbnmr#10]
Related to issues #8 and #9

**Comment by anbai106** [comment]
Hi, 

I was able to reinstall the new branch and test it using the downloaded data from UKB-RAP. I got the same error when running the function: "**remove_technical_variation(decoded)**", but it worked for function: "**extract_biomarkers(decoded**)". I have adapted the input data as the same format: **23774-0.1**. When you mentioned, did you change the new version to directly adapt the column names to be: "p23400_i0"? (See the version of the installed package to ensure the correct branch was installed)

The error message:

```
Checking for revelant UKB fields...
Extracting and pre-processing data...
Checking for required sample processing fields needed for QC procedure...
Processing sample processing fields for QC procedure...
Error in seq.int(rx[1L], rx[2L], length.out = nb) : 
  'from' must be a finite number
In addition: Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf
```

The version of the package: 
```
packageVersion('ukbnmr')
[1] ‘2.2.2’
```

**Comment by gemlahh** [comment]
> Hi,
> 
> I was able to reinstall the new branch and test it using the downloaded data from UKB-RAP. I got the same error when running the function: "**remove_technical_variation(decoded)**", but it worked for function: "**extract_biomarkers(decoded**)". I have adapted the input data as the same format: **23774-0.1**. When you mentioned, did you change the new version to directly adapt the column names to be: "p23400_i0"? (See the version of the installed package to ensure the correct branch was installed)
> 
> The error message:
> 
> ```
> Checking for revelant UKB fields...
> Extracting and pre-processing data...
> Checking for required sample processing fields needed for QC procedure...
> Processing sample processing fields for QC procedure...
> Error in seq.int(rx[1L], rx[2L], length.out = nb) : 
>   'from' must be a finite number
> In addition: Warning messages:
> 1: In min(x) : no non-missing arguments to min; returning Inf
> 2: In max(x) : no non-missing arguments to max; returning -Inf
> ```
> 
> The version of the package:
> 
> ```
> packageVersion('ukbnmr')
> [1] ‘2.2.2’
> ```

i have the same problem, do you solve it?

**Comment by sritchie73** [comment]
Hi @anbai106 , @gemlahh ,

I've now been able to debug directly on the RAP and solve the issue.

Can you try reinstalling from the UKB_RAP branch (`remotes::install_github("sritchie73/ukbnmr", "UKB_RAP", force=TRUE)`) and see if it works for you?

The underlying issue was the package wasn't correctly handling missing data for some QC flag columns as on the RAP they are loaded as character data with missing values set to "" rather than NA.

I've also updated the column name handling code to correctly handle array indices in the column names.

**Comment by sritchie73** [comment]
I plan to merge in these changes into the main branch and submit to CRAN once I update the documentation throughout to reflect that the RAP is now the new default with UKB's data analysis policy changes.

**Comment by gemlahh** [comment]
> I plan to merge in these changes into the main branch and submit to CRAN once I update the documentation throughout to reflect that the RAP is now the new default with UKB's data analysis policy changes.

thank you for your reply.
i tried your new resolution(remotes::install_github("sritchie73/ukbnmr", "UKB_RAP", force=TRUE)), there is one new bug::
processed <- remove_technical_variation(qc) 
Checking for relevant UKB fields...
Extracting and pre-processing data...
Checking for required sample processing fields needed for QC procedure...
Processing sample processing fields for QC procedure...
Determining log offsets for biomarker concentrations...
Adjusting for time between sample prep and sample measurement...
Error in qr.default(x): NA/NaN/Inf values are not allowed in function calls (arg1)
 Session Info:
R version 4.4.1 (2024-06-14 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 11 x64 (build 22631)

Matrix products: default


locale:
[1] LC_COLLATE=Chinese (Simplified)_China.utf8 
[2] LC_CTYPE=Chinese (Simplified)_China.utf8   
[3] LC_MONETARY=Chinese (Simplified)_China.utf8
[4] LC_NUMERIC=C                               
[5] LC_TIME=Chinese (Simplified)_China.utf8    

time zone: Asia/Shanghai
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ukbnmr_2.2.2

loaded via a namespace (and not attached):
 [1] tidyselect_1.2.1     DALEX_2.4.3          timeDate_4032.109   
 [4] libcoin_1.0-10       dplyr_1.1.4          TH.data_1.1-2       
 [7] pROC_1.18.5          caret_6.0-94         digest_0.6.36       
[10] rpart_4.1.23         timechange_0.3.0     lifecycle_1.0.4     
[13] processx_3.8.4       survival_3.6-4       magrittr_2.0.3      
[16] compiler_4.4.1       rlang_1.1.4          tools_4.4.1         
[19] utf8_1.2.4           Boruta_8.0.0         data.table_1.15.4   
[22] bit_4.0.5            pkgbuild_1.4.4       curl_5.2.1          
[25] plyr_1.8.9           multcomp_1.4-26      party_1.3-17        
[28] withr_3.0.1          purrr_1.0.2          desc_1.4.3          
[31] nnet_7.3-19          grid_4.4.1           stats4_4.4.1        
[34] fansi_1.0.6          colorspace_2.1-1     future_1.34.0       
[37] ggplot2_3.5.1        globals_0.16.3       scales_1.3.0        
[40] iterators_1.0.14     MASS_7.3-60.2        cli_3.6.3           
[43] mvtnorm_1.2-5        generics_0.1.3       remotes_2.5.0       
[46] rstudioapi_0.16.0    future.apply_1.11.2  reshape2_1.4.4      
[49] ggcorrplot_0.1.4.1   stringr_1.5.1        modeltools_0.2-23   
[52] splines_4.4.1        parallel_4.4.1       matrixStats_1.3.0   
[55] vctrs_0.6.5          hardhat_1.4.0        glmnet_4.1-8        
[58] Matrix_1.7-0         sandwich_3.1-0       callr_3.7.6         
[61] bit64_4.0.5          listenv_0.9.1        foreach_1.5.2       
[64] gower_1.0.1          tidyr_1.3.1          recipes_1.1.0       
[67] glue_1.7.0           parallelly_1.38.0    ps_1.7.7            
[70] codetools_0.2-20     lubridate_1.9.3      stringi_1.8.4       
[73] strucchange_1.5-4    shape_1.4.6.1        gtable_0.3.5        
[76] munsell_0.5.1        tibble_3.2.1         pillar_1.9.0        
[79] ipred_0.9-15         lava_1.8.0           R6_2.5.1            
[82] lattice_0.22-6       backports_1.5.0      CoxBoost_1.5        
[85] broom_1.0.6          class_7.3-22         Rcpp_1.0.13         
[88] nlme_3.1-164         prodlim_2024.06.25   coin_1.4-3          
[91] zoo_1.8-12           ModelMetrics_1.2.2.2 pkgconfig_2.0.3

thank you for your help!!!

**Comment by gemlahh** [comment]
> I plan to merge in these changes into the main branch and submit to CRAN once I update the documentation throughout to reflect that the RAP is now the new default with UKB's data analysis policy changes.

and my dataframe qc is this:
head(qc)[1:6]
      eid 23610-0.0 23635-0.0 23615-0.0 23590-0.0 23640-0.0
1 1000018        NA        NA        NA        NA        NA
2 1000020    65.141    47.879    69.823    26.739    50.206
3 1000037        NA        NA        NA        NA        NA
4 1000043        NA        NA        NA        NA        NA
5 1000051    70.403    49.115    72.071    27.284    50.936
6 1000066        NA        NA        NA        NA        NA

**Comment by sritchie73** [comment]
Hi @gemlahh 

Can you let me know how you've extracted the data and how you've loaded it into R? E.g. the options you used for the Table Exporter tool on the RAP, and the function you used to read in the data into R.

**Comment by gemlahh** [comment]
> Hi @gemlahh
> 
> Can you let me know how you've extracted the data and how you've loaded it into R? E.g. the options you used for the Table Exporter tool on the RAP, and the function you used to read in the data into R.

thank you for your patient reply.
i use Table Exporter tool to download the data, and the options used are default.
my dataframe qc is this:
head(qc)[1:6]
eid 23610-0.0 23635-0.0 23615-0.0 23590-0.0 23640-0.0
1 1000018 NA NA NA NA NA
2 1000020 65.141 47.879 69.823 26.739 50.206
3 1000037 NA NA NA NA NA
4 1000043 NA NA NA NA NA
5 1000051 70.403 49.115 72.071 27.284 50.936
6 1000066 NA NA NA NA NA

**Comment by gemlahh** [comment]
> Hi @gemlahh
> 
> Can you let me know how you've extracted the data and how you've loaded it into R? E.g. the options you used for the Table Exporter tool on the RAP, and the function you used to read in the data into R.
i use Table Exporter tool on the RAP to downloading the data, the options are default.
My downloading data's column name is "p23408_i0","p23588_i0"......(such as this format). And i transformed "p23588_i0"(original downloading format, "p23588_i0" is just an example) to "23588-0.0" (xxxx-0.0 this format to meet the function requirement), and i delete columns ending with "i1"(such as p23588_i1).
so the dateframe used for remove_technical_variation() ,the column name is such as "23588-0.0"
and the these 3 functions are ok:
nmr <- extract_biomarkers(decoded)
biomarker_qc_flags <- extract_biomarker_qc_flags(decoded)
sample_qc_flags <- extract_sample_qc_flags(decoded).
the warning occurs in remove_technical_variation()

**Comment by sritchie73** [comment]
Hi @gemlahh ,

With the update on the UKB_RAP branch there's no need to change any of the column names or delete columns ending with i1. Can you try running again without apply these extra steps after loading the data into R? If you want to filter to just measurements taken from blood samples collected at baseline assessment, you can filter the final table(s) to those with visit_index == 0.

**Comment by gemlahh** [comment]
> Hi @gemlahh ,
> 
> With the update on the UKB_RAP branch there's no need to change any of the column names or delete columns ending with i1. Can you try running again without apply these extra steps after loading the data into R? If you want to filter to just measurements taken from blood samples collected at baseline assessment, you can filter the final table(s) to those with visit_index == 0.

Thank you for your patient and detailed answers
something strange happened.
use your method, a new bug occured:
Checking for relevant UKB fields... 
Extracting and pre-processing data... 
Checking for required sample processing fields needed for QC procedure... 
Processing sample processing fields for QC procedure... 
Determining log offsets for biomarker concentrations... Adjusting for time between sample preparation and sample measurement... 
Error in qr.default(x): External function call cannot have NA/NaN/Inf (arg1)
this time i didn't change column. and even i delete na/nan/inf elements in my nmr dataframe, this bug still occured.

**Comment by sritchie73** [comment]
Hi @gemlahh ,

Can you run `str(extract_sample_qc_flags(decoded))` and copy the output here?

**Comment by gemlahh** [comment]
> Hi @gemlahh ,
> 
> Can you run `str(extract_sample_qc_flags(decoded))` and copy the output here?

str(extract_sample_qc_flags(qc_clean))
'data.frame':	259550 obs. of  13 variables:
 $ eid                          : int  1000020 1000051 1000079 1000084 1000092 1000107 1000110 1000128 1000135 1000144 ...
 $ visit_index                  : int  0 0 0 0 0 0 0 0 0 0 ...
 $ High.Lactate                 : chr  NA NA NA NA ...
 $ Low.Glucose                  : chr  NA NA NA NA ...
 $ High.Pyruvate                : chr  NA NA NA NA ...
 $ Low.Protein                  : chr  NA NA NA NA ...
 $ Processing.Batch             : chr  "Batch 7" "Batch 5" "Batch 2" "Batch 1" ...
 $ Sample.Measured.Date.and.Time: chr  "2021-05-18T19:09:59.000Z" "2020-02-18T15:56:16.000Z" "2019-07-29T23:07:18.000Z" "2019-06-07T22:55:35.000Z" ...
 $ Sample.Prepared.Date.and.Time: chr  "2021-05-18T10:22:16.000Z" "2020-02-17T11:45:56.000Z" "2019-07-29T03:26:38.000Z" "2019-06-06T11:06:40.000Z" ...
 $ Shipment.Plate               : chr  "Plate 0490000007579" "Plate 0490000007031" "Plate 0490000006249" "Plate 0490000006031" ...
 $ Spectrometer                 : chr  "Spectrometer 3" "Spectrometer 3" "Spectrometer 2" "Spectrometer 4" ...
 $ Well.Position.Within.Plate   : chr  "H02" "E10" "B05" "C10" ...
 $ Resolved.Plate.Swaps         : chr  NA NA NA NA ...

**Comment by sritchie73** [comment]
Hi @gemlahh ,

Thanks - I believe I've tracked down the problem. 

Can you install the latest update (`remotes::install_github("sritchie73/ukbnmr", "UKB_RAP", force=TRUE)`) and try again?

The date/time stamps in your data are in a different format to what I've seen when testing, so I've updated the code to use the lubridate package to harmonize the date/time stamps before computing the hours between sample prep and sample measurement, which previously would have been NA for your data.

**Comment by sritchie73** [comment]
Latest version of the package now fully supports analysis on the RAP

**Comment by anbai106** [comment]
Sorry for the late reply! I was busy with other things and am testing this now. Is it possible to have a toy/fake dataset (path/to/exported_ukbiobank_phenotype_data.csv) downloaded from UKB-RAP so users can adapt their input in case the format differs a little bit? e.g., the column header etc.

Never mind, I saw that you specify this in the README: https://dnanexus.gitbook.io/uk-biobank-rap/working-on-the-research-analysis-platform/accessing-data/accessing-phenotypic-data#database-columns

Thanks for maintaining this useful tool!

**Comment by sritchie73** [comment]
Hi @anbai106 

Yes, there's a toy dataset built into the package that is in the same format as the data on the UKB-RAP. This is loaded into your R session as `test_data` when you load the ukbnmr package and is also accessible by typing `ukbnmr::test_data` in your R session. You can write this out to a file, or save it as a new variable and modify the columns if you want to play around with it.
